import type { SceneCategory } from "./types";

export const colorEnvironmentCategory: SceneCategory = {
  key: "color_environment",
  label: "Environmental Color & Ambient Tone",
  order: 5,
  description:
    "Defines the natural or constructed colors present within the scene—wall colors, ambient glow, foliage tones, signage highlights, surface materials, and sky coloration. Helps maintain visual continuity as the camera moves through the environment.",
  properties: [
    {
      key: "dominant_environment_colors",
      label: "Dominant environment colors",
      type: "tags",
      description:
        "Major colors that define the environment's surfaces or atmosphere (e.g., warm beige walls, dark wood tones, neon magenta signage, blue-gray sky). Hex codes allowed.",
      options: [
        { value: "warm_beige", label: "Warm Beige" },
        { value: "cool_gray", label: "Cool Gray" },
        { value: "concrete_gray", label: "Concrete Gray" },
        { value: "forest_green", label: "Forest Green" },
        { value: "earth_brown", label: "Earth Brown" },
        { value: "sky_blue", label: "Sky Blue" },
        { value: "storm_gray", label: "Storm Gray" },
        { value: "brick_red", label: "Brick Red" },
        { value: "warm_wood_tones", label: "Warm Wood Tones" },
        { value: "neon_magenta", label: "Neon Magenta" },
        { value: "neon_cyan", label: "Neon Cyan" },
        { value: "golden_hour_glow", label: "Golden Hour Glow" },
        { value: "moonlit_blue", label: "Moonlit Blue" },
      ],
      allowCustom: true,
    },
    {
      key: "accent_colors",
      label: "Accent colors",
      type: "tags",
      description:
        "Secondary colors used for highlights, signage, textiles, trim, or objects that give the scene personality.",
      options: [
        { value: "warm_gold", label: "Warm Gold" },
        { value: "rose_gold", label: "Rose Gold" },
        { value: "bright_red", label: "Bright Red" },
        { value: "vivid_orange", label: "Vivid Orange" },
        { value: "sunny_yellow", label: "Sunny Yellow" },
        { value: "lime_green", label: "Lime Green" },
        { value: "aqua_teal", label: "Aqua Teal" },
        { value: "royal_blue", label: "Royal Blue" },
        { value: "electric_purple", label: "Electric Purple" },
        { value: "hot_pink", label: "Hot Pink" },
        { value: "neon_magenta", label: "Neon Magenta" },
        { value: "neon_cyan", label: "Neon Cyan" },
        { value: "arcane_violet", label: "Arcane Violet" },
        { value: "frost_blue", label: "Frost Blue" },
        { value: "pastel_pink", label: "Pastel Pink" },
        { value: "sage_green", label: "Sage Green" },
        { value: "steel_blue", label: "Steel Blue" },
      ],
      allowCustom: true,
    },
    {
      key: "restricted_colors",
      label: "Restricted / excluded colors",
      type: "tags",
      description:
        "Colors that should NOT appear in the scene, useful for maintaining palette discipline or avoiding unwanted drift.",
      options: [
        { value: "no_bright_red", label: "No Bright Red" },
        { value: "no_hot_pink", label: "No Hot Pink" },
        { value: "no_neon_green", label: "No Neon Green" },
        { value: "no_neon_colors", label: "No Neon Colors" },
        { value: "no_high_saturation", label: "No High Saturation Colors" },
        { value: "no_primary_colors", label: "No Primary Colors" },
        { value: "no_pastels", label: "No Pastels" },
        { value: "no_purple", label: "No Purple" },
        { value: "no_green_tints", label: "No Green Tints" },
        { value: "no_gold_tones", label: "No Gold Tones" },
        { value: "no_wood_browns", label: "No Wood Browns" },
        { value: "no_hologram_colors", label: "No Hologram Colors" },
      ],
      allowCustom: true,
    },
    {
      key: "ambient_color_tone",
      label: "Ambient color tone",
      type: "enum",
      description:
        "General color cast created by lighting, weather, or atmospheric conditions.",
      options: [
        { value: "neutral", label: "Neutral" },
        { value: "warm_amber", label: "Warm Amber" },
        { value: "golden_glow", label: "Golden Glow" },
        { value: "cool_blue", label: "Cool Blue" },
        { value: "moonlit_cool", label: "Moonlit Cool" },
        { value: "noir_muted", label: "Noir Muted" },
        { value: "storm_gray_blue", label: "Storm Gray-Blue" },
        { value: "neon_magenta_cast", label: "Neon Magenta Cast" },
        { value: "neon_cyan_cast", label: "Neon Cyan Cast" },
        { value: "arcane_violet_cast", label: "Arcane Violet Cast" },
      ],
      allowCustom: true,
    },
    {
      key: "surface_material_colors",
      label: "Surface/material color notes",
      type: "tags",
      description:
        "Optional descriptive notes for key surfaces (e.g., 'brick red walls', 'pale stone floor', 'dark metal machinery').",
      options: [
        { value: "light_wood", label: "Light Wood" },
        { value: "dark_wood", label: "Dark Wood" },
        { value: "pale_stone", label: "Pale Stone" },
        { value: "dark_slate", label: "Dark Slate" },
        { value: "brushed_steel", label: "Brushed Steel" },
        { value: "gunmetal_gray", label: "Gunmetal Gray" },
        { value: "matte_white_wall", label: "Matte White Wall" },
        { value: "warm_beige_wall", label: "Warm Beige Wall" },
        { value: "frosted_glass", label: "Frosted Glass" },
        { value: "smoked_glass", label: "Smoked Glass" },
        { value: "linen_beige", label: "Linen Beige" },
        { value: "velvet_burgundy", label: "Velvet Burgundy" },
        { value: "dark_carbon_fiber", label: "Dark Carbon Fiber" },
        { value: "matte_black_tech", label: "Matte Black Tech Surface" },
        { value: "glowing_runes_blue", label: "Glowing Runes (Blue)" },
        { value: "arcane_crystal_violet", label: "Arcane Crystal Violet" },
      ],
    },
    {
      key: "sky_color",
      label: "Sky color (if visible)",
      type: "tags",
      description:
        "Color description or hex code for the sky at this moment (e.g., '#B9D8FF', 'deep indigo', 'storm-gray'). Leave blank for indoor scenes.",
      options: [
        { value: "clear_blue", label: "Clear Blue" },
        { value: "overcast_gray", label: "Overcast Gray" },
        { value: "storm_gray", label: "Storm Gray" },
        { value: "golden_hour_amber", label: "Golden Hour Amber" },
        { value: "warm_orange_sunset", label: "Warm Orange Sunset" },
        { value: "dusky_violet", label: "Dusky Violet" },
        { value: "indigo_twilight", label: "Indigo Twilight" },
        { value: "midnight_blue", label: "Midnight Blue" },
        { value: "moonlit_silver_blue", label: "Moonlit Silver-Blue" },
        { value: "magenta_nebula", label: "Magenta Nebula Sky" },
        { value: "crystal_cyan_sky", label: "Crystal Cyan Sky" },
      ],
    },
    {
      key: "light_reflection_color",
      label: "Light reflection / bounce color",
      type: "tags",
      description:
        "Optional description of reflected color in the environment (e.g., 'neon pink bouncing off wet pavement', 'golden hour light reflecting on windows').",
      options: [
        { value: "golden_reflection", label: "Golden Reflection" },
        { value: "warm_amber_reflection", label: "Warm Amber Reflection" },
        { value: "cool_blue_reflection", label: "Cool Blue Reflection" },
        {
          value: "moonlit_silver_reflection",
          label: "Moonlit Silver Reflection",
        },
        { value: "neon_magenta_reflection", label: "Neon Magenta Reflection" },
        { value: "neon_cyan_reflection", label: "Neon Cyan Reflection" },
        {
          value: "streetlight_yellow_reflection",
          label: "Streetlight Yellow Reflection",
        },
        {
          value: "arcane_violet_reflection",
          label: "Arcane Violet Reflection",
        },
        { value: "crystal_cyan_reflection", label: "Crystal Cyan Reflection" },
      ],
    },
    {
      key: "color_notes",
      label: "Additional color notes",
      type: "tags",
      description:
        "Freeform guidance for subtle color logic (e.g., 'avoid green in this room', 'orange signage is the primary brand color', 'purple glow appears only near artifact').",
      options: [
        { value: "limited_palette_feel", label: "Limited Palette Feel" },
        { value: "two_tone_bias", label: "Two-Tone Bias" },
        { value: "cool_palette_bias", label: "Cool Palette Bias" },
        { value: "warm_palette_bias", label: "Warm Palette Bias" },
        { value: "somber_color_mood", label: "Somber Color Mood" },
        { value: "dreamy_color_mood", label: "Dreamy Color Mood" },
        { value: "neon_highlights", label: "Neon Highlights" },
        { value: "glow_subtle", label: "Subtle Glow Accents" },
        {
          value: "weathered_surface_colors",
          label: "Weathered Surface Colors",
        },
        { value: "emphasize_story_colors", label: "Emphasize Story Colors" },
        {
          value: "consistent_character_color_cues",
          label: "Consistent Character Color Cues",
        },
      ],
    },
  ],
};
